#!/bin/sh
# you can think of this more as post-wm setup

set_walls() {
	for i in $(xrandr | grep ' connected' | cut -d' ' -f1); do
		xwallpaper --output $i --zoom ~/.local/share/pape.jpg
	done
}

screensaver () {
	pkill xscreensaver
	HOME=".config/xscreensaver" xscreensaver --no-splash &
}

keyboard () {
	setxkbmap -option caps:super
	pkill xcape
	xcape -e 'Super_L=Escape'
	xset -q | grep "Caps Lock:\s*on" && xdotool key Caps_Lock
	xset r rate 200 40
}

# initial post-wm setup
keyboard
statuswrap
set_walls
screensaver

find_card_pci() {
	[ -z $pci_path ] && pci_path=$(find /sys/devices | \
		grep edid | \
		cut -d/ -f1-6
	)
}

assert_edid() {
	find_card_pci

	out=$(sha256sum ${pci_path}/card0/card0-$1/edid | \
		cut -d' ' -f1)

	[ "$out" = "$2" ] && return 0 || return 1
}

exists() {
	xrandr | grep ' connected' | grep -c "${1}"
}
case "$(hostname)" in
	"mainsail")
		echo "mainsail"
		xrandr --output VGA-1 --left-of HDMI-1
		bspc monitor VGA-1 -d 1 3 5 7 9
		bspc monitor HDMI-1 -d 2 4 6 8 0
		;;
	"mlg")
		xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 120 --pos 0x0 --rotate normal \
			--output DP-1-2 --mode 1920x1080 --rate 120 --pos 1920x0 --rotate normal \
			--output DP-0 --off \
			--output DP-1-1 --off
		xinput set-prop 'INSTANT USB GAMING MOUSE ' 338 -1
		;;
	"x230t")
		echo "x230t"
		case "$1" in
			"dockedtwo")
				# assume we're connected to the two external displays
				xrandr --output VGA-1 --primary --mode 1920x1080 --rotate normal \
					--output HDMI-1 --mode 1920x1080 --rotate normal --right-of VGA-1 \
					--output LVDS-1 --off
				bspc monitor VGA-1 -d 1 3 5 7 9
				bspc monitor HDMI-1 -d 2 4 6 8
				;;
			*)
				if
					assert_edid "VGA-1" "35737dc483d2c3b1b20ea2343ce13c6c42d115febdc9634f8437e1b9f7fd3f5c" &&
					assert_edid "HDMI-A-1" "01887cbd23d74201e489a6334656f7db73a7b7f732a738a9f1ee2d53389f7817";
				then
					echo "docked"
					xrandr --output LVDS-1 --primary --mode 1366x768 --pos 1194x1080 --rotate normal \
						--output VGA-1 --mode 1920x1080 --pos 0x0 --rotate normal \
						--output HDMI-1 --mode 1920x1080 --pos 1920x0 --rotate normal \
						--output DP-1 --off \
						--output HDMI-2 --off \
						--output DP-2 --off
					bspc monitor LVDS-1 -d 1 4 7
					bspc monitor VGA-1 -d 2 5 8
					bspc monitor HDMI-1 -d 3 6 9
				else
					bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8 9
				fi
				;;
		esac
		;;
esac
