#!/bin/sh

case $1 in
	"regular")
		khal new -a home $2 07:40 08:28 Spanish I H
		khal new -a home $2 08:34 09:21 AP Human Geography
		khal new -a home $2 09:27 09:52 SAIL
		khal new -a home $2 09:58 10:45 Symphonic Band
		khal new -a home $2 10:51 11:38 English I H
		khal new -a home $2 11:38 12:07 Lunch
		khal new -a home $2 12:13 13:00 Biology I H
		khal new -a home $2 13:06 13:53 Study Hall
		khal new -a home $2 13:59 14:47 Algebra II H
		;;
	"late")
		khal new -a home $2 08:40 08:28 Spanish I H
		khal new -a home $2 08:34 09:21 AP Human Geography
		khal new -a home $2 09:27 09:52 SAIL
		khal new -a home $2 09:58 10:45 Symphonic Band
		khal new -a home $2 10:51 11:38 English I H
		khal new -a home $2 11:38 12:07 Lunch
		khal new -a home $2 12:13 13:00 Biology I H
		khal new -a home $2 13:06 13:53 Study Hall
		khal new -a home $2 13:59 14:47 Algebra II H
		;;
esac
