#!/bin/sh

geos=$(
	xrandr | \
	grep ' connected' | \
	grep -o '[0-9]*x[0-9]*+[0-9]*+[0-9]*' | \
	awk -F'[x+]' '{print $1 "x20+" $3 "+" $4}'
)

pkill statusbar

for i in $geos; do
	st -c statusbar -p -g "$i" -e statusbar & disown
done
