#!/bin/sh

exists() {
	xrandr | grep ' connected' | grep "${1}" | wc -l
}

if [ $(exists "HDMI-2") -eq 1 ] && [ $(exists "LVDS-1") -eq 1 ]; then
	printf "two"
	xrandr --output HDMI-2 --right-of LVDS-1 --auto
	xrandr --output VGA-1 --off --auto
	bspc monitor LVDS-1 -d I II III IV V VI VII VIII IX X
	bspc monitor HDMI-2 -d I II III IV V VI VII VIII IX X
	exit 0
fi

if [ $(exists "HDMI-2") -eq 1 ]; then
	printf "one"
	xrandr --output LVDS-1 --off --auto
	xrandr --output VGA-1 --off --auto
	bspc monitor -d I II III IV V VI VII VIII IX X
	bspc monitor -g 1680x1050+0+0
	exit 0
fi

if [ $(exists "LVDS-1") -eq 1 ]; then
	bspc monitor -d I II III IV V VI VII VIII IX X
	bspc monitor LVDS-1 -a I II III IV V VI VII VIII IX
	exit 0
fi
