#!/bin/sh

scripts="$(
	find /home/usr/git/utils/sh /home/usr/git/utils/c -type f |
	grep -v '\.git' |
	xargs file |
	grep 'C source \|POSIX shell script' |
	awk -F':' '{print $1}' |
	fzy
)"

[ -z "$scripts" ] || nvim "$scripts"
