#!/bin/sh

pulse=$(pgrep -c pulseaudio)

[ "$1" = "inc" ] && sign="+"
[ "$1" = "dec" ] && sign="-"

[ "$#" -eq 0 ] && exit 1

if [ "$pulse" -eq 1 ]; then
	for SINK in $(pacmd list-sinks | grep 'index:' | cut -b12-)
	do
		pactl set-sink-volume "$SINK" "${sign}5%"
	done
else
	amixer -c 0 set Master "5%${sign}"
fi

killall -12 status
