#!/bin/sh

if [ -d "$HOME/dot_testing" ]; then
	cd ~/dot_testing
elif [ -d "$HOME/dots" ]; then
	cd ~/dots
fi

machine=$(hostname)

if [ "$machine" = "localhost" ]; then
	machine="phone"
fi

sh boxes/$machine/custom_command $@
