#!/bin/sh
# rndusr's bspwmrc

# post-wm boilerplate
disp
statusbar &

# set up the color scheme
bspc config normal_border_color "#161510"
bspc config active_border_color "#727A18"
bspc config focused_border_color "#727A18"

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config window_gap 3
bspc config top_padding 20

bspc rule -a st-gpg-menu state=floating
bspc rule -a statusbar border=off sticky=on state=floating manage=off
bspc rule -a tmenu-prompt border=on sticky=on state=floating
