#!/bin/sh
# rndusr's bspwmrc

# get the monitors up and running
bspc monitor -d 1 2 3 4 5 6 7 8 9

# set up the color scheme
bspc config normal_border_color "#161510"
bspc config active_border_color "#727A18"
bspc config focused_border_color "#727A18"

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config top_padding 20

bspc rule -a st-gpg-menu state=floating
bspc rule -a statusbar border=off sticky=on state=floating manage=off
