#!/bin/bash

# if not interactive, don't do anything
[ -z "$PS1" ] && return

open-port () {
	sudo iptables -A INPUT -p tcp --dport $1 -j ACCEPT
}

# some housekeeping
alias ls="ls --color=auto --group-directories-first"
alias weather="curl https://wttr.in"
alias lynx="lynx -cfg=$LYNX_CFG_PATH/lynx.cfg"
alias elinks="TERM='xterm-color' elinks"
alias pkgsearch="nix search nixpkgs"
alias reload=". ~/.config/bash/profile"
alias shuttle="sshuttle -r netbox.s 0/0 --dns"
alias synctunnel="ssh -N -L localhost:22001:localhost:22000 -R localhost:22001:localhost:22000 netbox & syncthing"
alias e="emacsclient"

function cd() {
	builtin cd "$@" && ls --color=auto --group-directories-first
}

# history
HISTCONTROL=ignorespace:ignoredups:erasedups
HISTFILESIZE=9999999999
HISTSIZE=9999999999

# bash specific settings
set -o vi # vim mode
shopt -s autocd
shopt -s cmdhist
shopt -s histreedit
shopt -s histappend
shopt -s histverify

PS1="\w\$ "

if [ -n "$IN_NIX_SHELL" ]; then
	NIX_SHELL_PS1="nix:"
fi

if [ "$USER" = "root" ]; then
	USER_PREFIX="\[\033[41m\]root:\[\033[0;0m\]"
elif [ "$USER" == "ryan" ] && [ "$HOSTNAME" = "netbox" ]; then
	USER_PREFIX=""
elif [ "$USER" != "usr" ]; then
	USER_PREFIX="$USER:"
fi

# hostname shenanigans
case "$HOSTNAME" in
	"aristotle")
		PS1="$USER_PREFIX\[\033[36;1m\]${NIX_SHELL_PS1}arist:$PS1\[\033[0;0m\]"
		;;
	"copernicus")
		PS1="$USER_PREFIX\[\033[97;1m\]${NIX_SHELL_PS1}coper:$PS1\[\033[0;0m\]"
		;;
	"netbox")
		PS1="$USER_PREFIX\[\033[95;1m\]${NIX_SHELL_PS1}net:$PS1\[\033[0;0m\]"
		;;
	"plato")
		PS1="$USER_PREFIX\[\033[32;1m\]${NIX_SHELL_PS1}plato:$PS1\[\033[0;0m\]"
		;;
	"hammurabi")
		PS1="$USER_PREFIX\[\033[33;1m\]${NIX_SHELL_PS1}ham:$PS1\[\033[0;0m\]"
		;;
	*)
		PS1="$USER_PREFIX\[\033[96;1m\]${NIX_SHELL_PS1}unk:$PS1\[\033[0;0m\]"
		;;
esac

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec sx; fi
