#!/bin/bash

# some housekeeping
shopt -s autocd
alias rc=". ~/.config/bash/bashrc"
alias erc="nvim ~/.config/bash/bashrc"
alias reload=". ~/.config/bash/bashrc"

alias sched="nvim $DOTREMINDERS"
alias cal="rem -cl"
alias shutdown="sudo shutdown -h now"
alias ls="ls --color=auto"
alias ll="ls -lah --color=auto"
alias irssi="irssi --home=$HOME/.config/irssi"

PS1="\w\$ "

repos() {
	sel="$(ls ~/git | fzy | awk '{print "/home/usr/git/"$1}')"
	[ "$?" -eq 1 ] && exit

	cd "$sel"
}

rss() {
	cd ~/.local/share/sfeed/
	touch .urls
	sfeed_curses *
	cd -
}
