#!/bin/sh

bspc rule -a st-gpg-menu state=floating
bspc rule -a statusbar border=off sticky=on state=floating manage=off
bspc rule -a tmenu-prompt border=on sticky=on state=floating
bspc rule -a Xmessage border=on state=floating
bspc rule -a Zathura state=tiled
bspc rule -a generic-st-window state=floating manage=on sticky=on border=on
bspc rule -a floating-feh state=floating
bspc rule -a *:*:'phonercon' desktop=phonercon
bspc rule -a send-to-9 desktop=09

bspc config normal_border_color "#161510"
bspc config active_border_color "#161510"
bspc config focused_border_color "#727A18"

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config window_gap 0
bspc config top_padding 20

bspc desktop -f 01

set_walls() {
	for i in $(xrandr | grep ' connected' | cut -d' ' -f1); do
		xwallpaper --output $i --zoom ~/.local/share/pape.jpg
	done
}
screensaver () {
	pkill xscreensaver
	mkdir -p ~/.config/xscreensaver
	HOME=".config/xscreensaver" xscreensaver --no-splash & 2>&1 > /dev/null
}
start_statusbar () {
	pkill statusbar
	statusbar start_statusbars
}
keyboard () {
	setxkbmap -option caps:super
	pkill xcape
	xcape -e 'Super_L=Escape'
	xkbset bo 50
	xkbset exp =bo
	xset -q | grep "Caps Lock:\s*on" && xdotool key Caps_Lock
	xset -r 161 # tablet rotate key doesn't need repeat
	xset r rate 300 80
}

desktops="01 02 03 04 05 06 07 08 09"
case "$(hostname)" in
	"aristotle")
		bspc monitor eDP-1 -d $desktops
		;;
	"copernicus")
		bspc monitor DP-0 -d $desktops phonercon aristrcon
		if ! pkill -c scrcpy; then
			bspwm-copernicus-welcome
		fi
		;;
	"localhost") # phone in termux
		xrandr --output VNC-0 --mode 1920x1080
		bspc monitor VNC-0 -d $desktops
		feh --bg-fill ~/.local/share/pape.jpg
		bspc config top_padding 0
		bspc config bottom_padding 100
		mkdir -p ~/.cache/statusbar
		pgrep -a st | \
			grep statusbar | \
			awk '{print $1}' | \
			xargs kill
		termux-statusbar-polyfill start_statusbars
		;;
esac

set_walls
screensaver
start_statusbar
keyboard
