#!/bin/sh

hostname=$(hostname)

if [ "$hostname" != "copernicus" ]; then
	echo "this script should be run only on copernicus"
	exit 1
fi

if [ "$1" = "umount" ]; then
	sudo umount ~/mount
	sudo mdadm --stop /dev/md0

	echo "done"
	exit 0
fi

sudo mdadm --assemble --run /dev/md0 /dev/sdb2 /dev/sdc2
mkdir -p ~/mount
sudo mount /dev/md0 ~/mount
