#!/bin/sh

[ -z "$1" ] && exit 1

# wrap rbw get $1 --full to output in the git credential helper
# format

if [ "$HOSTNAME" != "aristotle" ]; then
	rbw-x11-prompt
fi

# username=yourusername
# password=yourpassword

output=$(rbw get $1 --full)
echo "$output" | \
	sed '1{s/^/password=/}' | \
	sed 's/Username: /username=/g' | \
	grep -E 'username|password' | \
	tac
