#!/bin/sh

print_help() {
	echo "
rotate -- a thin wrapper around imagemagick

$1 - degrees (clockwise)
$2 - infile
$3 - outfile"

exit
}

if [ "$1" = "-h" ]; then
	print_help
fi

if [ -z "$1" ]; then
	print_help
fi

[ -z "$3" ] && 3="$2.out"
convert "$1" -rotate "$2" "$3"
