#!/bin/sh

tmenu_path () {
    IFS=" :"
    for i in $PATH; do
        for j in "$i"/*; do
            [ -f "$j" ] && [ -x "$j" ] && printf "%s\n" "$j" | xargs basename
        done
    done
}

export IS_RUNNING_IN_TMENU="yes"
choice=$(echo regenerate | cat $HOME/.local/share/tmenu_cache - | tmenu)
if [ "$choice" = "regenerate" ]; then
	mkdir -p $HOME/.local/share
	tmenu_path | sort > $HOME/.local/share/tmenu_cache
else
	/bin/sh -c $choice &
fi
