#!/bin/sh

# access gemini and gopher urls within vimb with vulpes proxy

# yes, this will result in urls like
# 'proto://host.tld/page?q="://" becoming
# 'proto/host.tld/page?q="/"
stripped_url=`printf "%s" $1 | sed 's|://|/|g'`

# use xdotool to type the correct commands into the vimb
# window, assuming that the window is currently focused (which
# happens most of the time)
xdotool key Escape
xdotool key Escape
xdotool type "ohttp://proxy.vulpes.one/${stripped_url}"
xdotool key Return

exit 0
