#!/bin/sh
# rndusr's bspwmrc

bspc rule -a st-gpg-menu state=floating
bspc rule -a statusbar border=off sticky=on state=floating manage=off
bspc rule -a tmenu-prompt border=on sticky=on state=floating
bspc rule -a Xmessage border=on state=floating
bspc rule -a Zathura state=tiled
bspc rule -a generic-st-window state=floating manage=on sticky=on border=on
bspc rule -a floating-feh state=floating

set_walls() {
	for i in $(xrandr | grep ' connected' | cut -d' ' -f1); do
		xwallpaper --output $i --zoom ~/.local/share/pape.jpg
	done
}

# post-wm boilerplate
disp
statuswrap
set_walls
pkill xscreensaver
HOME=".config/xscreensaver" xscreensaver --no-splash &

# set up the color scheme
bspc config normal_border_color "#161510"
bspc config active_border_color "#727A18"
bspc config focused_border_color "#727A18"

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config window_gap 0
bspc config top_padding 20
