#!/bin/bash

# some housekeeping
set -o vi
shopt -s autocd
alias rc=". ~/.config/bash/bashrc"
alias erc="nvim ~/.config/bash/bashrc"
alias reload=". ~/.config/bash/bashrc; . ~/.config/bash/profile"

# ssh keeping tidy
alias ssh="ssh -F $HOME/.config/ssh/config"

# remind alias
alias sched="nvim $DOTREMINDERS"
alias cal="rem -cl"
alias shutdown="sudo shutdown -h now"

alias ls="ls --color=auto"
alias irssi="irssi --home=$HOME/.config/irssi"

PS1="\w\$ "

# repos func
repos() {
	sel="$(ls ~/git | fzy | awk '{print "/home/usr/git/"$1}')"
	[ "$?" -eq 1 ] && exit

	cd "$sel"
}

files() {
	sel=$(find /home/$(whoami) |
		grep -v '\.cache\|\.pki\|/scratch/\|\.config/chromium\|\.git\|\.local/lib\|\.mozilla/firefox/' |
		fzy -l 50)
	[ -z "$sel" ] && return 1
	[ -d "$sel" ] && cd "$sel" || nvim "$sel"
	return 0
}

rss() {
	cd ~/.local/share/sfeed/
	sfeed_curses *
	cd -
}

alias f=files
