#!/bin/bash

# program exports to keep the $HOME neat and tidy
# bash
export HISTFILE="$HOME/.config/bash/hist"
export HISTFILESIZE=3000

# python
export PYTHONSTARTUP="$HOME/.config/python/pythonrc.py"

# less
export LESSHISTFILE="-"

# gnupg
export GNUPGHOME="$HOME/.local/share/gnupg"

# remind
export DOTREMINDERS="$HOME/git/calendar/reminders"

# XDG config
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# reminders
export DOTREMINDERS="$XDG_DATA_HOME/reminders/remind"

# source the bashrc(s)
[ -f $HOME/.config/bash/bashrc ] && . $HOME/.config/bash/bashrc
[ -f $HOME/.bashrc ] && . $HOME/.bashrc
