#!/bin/bash

# program exports to keep the $HOME neat and tidy
# bash
export HISTFILE="$HOME/.config/bash/hist"
export HISTFILESIZE=3000

# python
export PYTHONSTARTUP="$HOME/.config/python/pythonrc.py"

# less
export LESSHISTFILE="-"

# remind
export DOTREMINDERS="$HOME/git/calendar/reminders"

# source the bashrc(s)
[ -f $HOME/.config/bash/bashrc ] && . $HOME/.config/bash/bashrc
[ -f $HOME/.bashrc ] && . $HOME/.bashrc
